name: Application Deploy
on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo "${{ github.head_ref || github.ref_name }}"
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
    
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ${{ secrets.MOVIES_PROJECT_DIR }};
            git checkout ${{ github.head_ref || github.ref_name }};
            git pull origin ${{ github.head_ref || github.ref_name }};
            docker-compose up --build -d
